### ISSUE TITLE
[Feature] Show CNI in kubernetes

### ISSUE THREAD

**Issue by patsevanton** [jkulzer/kubefetch#10]
Thanks for kubefetch!
Please show CNI in kubernetes

**Comment by jkulzer** [comment]
The way to show the used CNI Plugin is now added! (https://github.com/jkulzer/kubefetch/commit/bbf931122bdb4442d5a945409bc2fd0108c589be)

A release should have been built using Github Actions

It uses the images in the kube-system namespace to detect which CNI you are running. I currently only have a K3s cluster running Cilium, so I have no way to verify the functionality of the detection of the other CNIs.

The currently supported CNIs are: **Cilium**, **Calico**, **Weave Net** and **Flannel**

Feel free to reopen this issue if your CNI doesn't get recognized!
