### ISSUE TITLE
Release version / Binary version mismatch

### ISSUE THREAD

**Issue by wrmilling** [jkulzer/kubefetch#18]
Looks like the version has not been updated in the `-version` command for the last two releases. Minor thing, but had me confused that packaging didn't work on last update. 

https://github.com/jkulzer/kubefetch/blob/main/kubefetch.go#L43

**Comment by jkulzer** [comment]
Hello! Thanks for pointing that out, I usually forget about this. Bumped the version there now (https://github.com/jkulzer/kubefetch/pull/21).
