### ISSUE TITLE
Add age of oldest node

### ISSUE THREAD

**Issue by billimek** [jkulzer/kubefetch#7]

**Comment by jkulzer** [comment]
@billimek I assumed you want to get the age of the entire cluster, so I added another point to the list to show the age of the cluster.

The age is shown in days, not in years and days. Please reopen the issue if this looks ugly to you.

I only have one node in my cluster currently, so i have not way to test if it correctly grabs the oldest node.

The commit in question: https://github.com/jkulzer/kubefetch/commit/21f090431ddf43cde46ac2330e1252b0d9b91ba4

You can close this if you are happy with the feature!

**Comment by billimek** [comment]
Thank you for doing this!  I was actually just sitting down to try to code this feature and submit it, and you already did so!

It works great as-is IMO, thank you again!
![image](https://github.com/jkulzer/kubefetch/assets/6393612/882bc3d8-93b4-499b-8e1a-7ecd5917985b)

**Comment by jkulzer** [comment]
Nice! Thank you for using my software!
